services:
  db:
    image: postgres:15
    container_name: wallet-db-dev
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: wallet
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: dockerfile.dev
    container_name: wallet-api-dev
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
      - "5555:5555"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/wallet
      JWT_SECRET: your_jwt_secret_key
      JWT_EXPIRES_IN: 3600
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: npm run dev

volumes:
  postgres_dev_data:
  node_modules: